# Generated by Django 3.2.3 on 2021-06-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('guardian', '0002_generic_permissions_index'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
