# Generated by Django 3.2.3 on 2021-06-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_division_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='dev_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
