# Generated by Django 3.2.3 on 2021-06-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_division_dev_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='alias',
        ),
    ]
