# Generated by Django 3.2.3 on 2021-06-04 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_organization_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='alias',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
