# Generated by Django 3.2.3 on 2021-06-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='profile',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(blank=True, choices=[('AirlineAgent', 'AirlineAgent'), ('WRHAgent', 'WRHAgent'), ('AirportAgent', 'AirportAgent')], max_length=100, null=True),
        ),
    ]
